include: "rules/common.smk"
include: "rules/pre_align_qc.smk"
include: "rules/align.smk"
include: "rules/post_align_qc.smk"
include: "rules/peaks.smk"
include: "rules/bw.smk"


peaks = expand("results/peaks/{chip_sample}/{chip_sample}_peaks.narrowPeak", chip_sample = chip_samples)
bw = expand("results/bw/{sample}.bw", sample = samples)
qc = ["results/qc/multiqc/multiqc_report.html"]
out_files = peaks + bw + qc

rule all:
	input:
		out_files
	
onsuccess:
	shell("if command -v telegram-notify; then telegram-notify --success --text \'snakemake:chipseq:{} completed\'; fi".format(run_name.replace("_", "\\_")))

onerror:
	shell("if command -v telegram-notify; then telegram-notify --error --text \'snakemake:chipseq:{} failed\'; fi".format(run_name.replace("_", "\\_")))
