# labname to include in bam header
labname: ''
# name of the seqeucing platform
platform: 'ILLUMINA'
# path to blacklist regions
blklist_regions: 'data/external/blacklist/blacklist.bed'
# path to genome sizes file
genome_sizes: 'data/external/ref/fa/genome.chrom.sizes'
# genome for methods
genomes: 'hg19'


# used to align single end reads to the ref genome
bowtie:
  # -m <int>           suppress all alignments if > <int> exist (def: no limit)
  max_multiple_aln: 2
  # -k <int>           report up to <int> good alignments per read (default: 1)
  max_aln_per_read: 2
  # --chunkmbs <int>   max megabytes of RAM for best-first search frames (def: 64)
  chunkmbs: 250
  # idx location
  idx: "data/external/ref/genome"

macs2:
  # -g GSIZE, --gsize GSIZE
  #                       Effective genome size. It can be 1.0e+9 or 1000000000,
  #                       or shortcuts:'hs' for human (2.7e9), 'mm' for mouse
  #                       (1.87e9), 'ce' for C. elegans (9e7) and 'dm' for
  #                       fruitfly (1.2e8), Default:hs
  gsize: 'hs'
  # -q QVALUE, --qvalue QVALUE
  #                       Minimum FDR (q-value) cutoff for peak detection.
  #                       DEFAULT: 0.05. -q, and -p are mutually exclusive.
  qvalue: 0.01




# ----------------addons----------------
addons:
  # Trim/Remove adapters from the reads?
  trimgalore: true

trimgalore:
  # -q/--quality <INT>     Trim low-quality ends from reads in addition to adapter removal. For                                                                                                                       
  #                       RRBS samples, quality trimming will be performed first, and adapter                                                                                                                        
  #                       trimming is carried in a second round. Other files are quality and adapter                                                                                                                 
  #                       trimmed in a single pass. The algorithm is the same as the one used by BWA                                                                                                                 
  #                       (Subtract INT from all qualities; compute partial sums from all indices                                                                                                                    
  #                       to the end of the sequence; cut sequence at the index at which the sum is                                                                                                                  
  #                       minimal). Default Phred score: 20.  
  quality: 10
  # --stringency <INT>    Overlap with adapter sequence required to trim a sequence. Defaults to a
  #                      very stringent setting of 1, i.e. even a single bp of overlapping sequence                                                                                                                 
  #                      will be trimmed off from the 3' end of any read. 
  stringency: 5
  # -e <ERROR RATE>         Maximum allowed error rate (no. of errors divided by the length of the matching
  #                       region) (default: 0.1)
  e: 0.1
