include: "src/common.smk"
include: "src/addons.smk"
include: "src/align.smk"
include: "src/peaks.smk"
include: "src/bw.smk"
include: "src/qc.smk"

rule all:
	input:
		expand("results/peaks/{chip_sample}/{chip_sample}_filt_peaks.bed", chip_sample = chip_samples),
		expand("results/bw/{chip_sample}-{bdg_type}.bw", chip_sample = chip_samples, bdg_type = bdg_types),
		"results/qc/multiqc/multiqc_report.html"
		
onsuccess:
	shell("if command -v telegram-notify; then telegram-notify --success --text \'snakemake:chipseq:{} completed\'; fi".format(run_name))

onerror:
	shell("if command -v telegram-notify; then telegram-notify --error --text \'snakemake:chipseq:{} failed\'; fi".format(run_name))
